-- =============================================================================
-- The Book — BASELINE SCHEMA CAPTURE
-- =============================================================================
-- This is NOT the original migration history. The database was built manually
-- in the Supabase dashboard, so no migration files existed. This file is a
-- best-effort baseline reconstructed from CODE ANALYSIS (every supabase.from()
-- call, every .select()/.insert()/.update() in the app) plus the column lists
-- confirmed via live REST probes during the security-hardening session.
--
-- CONFIDENCE:
--   * providers / bookings / clients  -> column lists CONFIRMED via live probe.
--   * all other tables                -> columns INFERRED from code usage; types
--                                        are reasonable guesses. Production may
--                                        have additional columns not captured here.
--
-- SAFETY:
--   * Every CREATE TABLE uses IF NOT EXISTS, so running this against a database
--     that already has these tables is a no-op for those tables (it will NOT
--     add missing columns to an existing table — CREATE TABLE IF NOT EXISTS
--     skips the whole statement if the table exists).
--   * Buckets use ON CONFLICT DO NOTHING. Triggers/functions use CREATE OR
--     REPLACE + DROP TRIGGER IF EXISTS.
--   * RLS POLICIES are the *intended* hardened baseline (from the audit). They
--     use DROP POLICY IF EXISTS + CREATE POLICY, which means running this on an
--     EXISTING production DB would REPLACE whatever policies are live. Do NOT
--     blindly run the RLS section against production — see supabase/README.md.
--
-- Primary use: bootstrap a FRESH Supabase project to a working approximation of
-- production. See supabase/README.md for the full engineer handoff + gaps list.
-- =============================================================================

create extension if not exists pgcrypto;

-- =============================================================================
-- 1. CATALOG / IDENTITY
-- =============================================================================

create table if not exists public.categories (
  id   bigint generated by default as identity primary key,
  name text not null
);

create table if not exists public.providers (
  id                         uuid primary key default gen_random_uuid(),
  user_id                    uuid references auth.users(id) on delete cascade,
  display_name               text,
  username                   text unique,
  category_id                bigint references public.categories(id),
  bio                        text,
  location                   text,
  neighborhood               text,
  profile_photo_url          text,
  cover_image_url            text,
  specialties                text[] not null default '{}',
  profile_style              text,
  years_experience           integer,
  created_at                 timestamptz not null default now(),
  updated_at                 timestamptz,
  -- denormalized metrics (trigger / job maintained)
  total_bookings             integer not null default 0,
  completed_count            integer not null default 0,
  no_show_count              integer not null default 0,
  late_count                 integer not null default 0,
  rating                     numeric not null default 0,
  average_rating             numeric not null default 0,
  review_count               integer not null default 0,
  follower_count             integer not null default 0,
  bookings_this_week         integer not null default 0,
  bookings_this_month        integer not null default 0,
  repeat_client_rate         numeric not null default 0,
  next_available             timestamptz,
  -- payments / stripe connect
  stripe_account_id          text,
  stripe_onboarding_complete boolean not null default false,
  stripe_charges_enabled     boolean not null default false,
  stripe_payouts_enabled     boolean not null default false,
  stripe_details_submitted   boolean not null default false,
  stripe_account_updated_at  timestamptz,
  payment_mode               text,
  deposit_type               text,
  deposit_value              numeric,
  issue_window_hours         integer,
  -- placement / trust flags (PRIVILEGED — see REVOKE section below)
  is_demo                    boolean not null default false,
  is_trending                boolean not null default false,
  is_featured                boolean not null default false,
  is_approved                boolean not null default false,
  verification_status        text not null default 'pending',
  identity_verified          boolean not null default false,
  business_verified          boolean not null default false,
  verification_submitted_at  timestamptz,
  verification_notes         text
);

create table if not exists public.clients (
  id           uuid primary key references auth.users(id) on delete cascade,
  name         text,
  notes        text,
  avatar_url   text,
  neighborhood text,
  created_at   timestamptz not null default now()
);

create table if not exists public.provider_services (
  id               uuid primary key default gen_random_uuid(),
  provider_id      uuid references public.providers(id) on delete cascade,
  name             text,
  description      text,
  price            numeric not null default 0,
  duration_minutes integer,
  is_active        boolean not null default true,
  sort_order       integer,
  created_at       timestamptz not null default now()
);

create table if not exists public.provider_availability (
  id           uuid primary key default gen_random_uuid(),
  provider_id  uuid references public.providers(id) on delete cascade,
  day_of_week  integer,
  start_time   time,
  end_time     time,
  is_available boolean not null default true,
  created_at   timestamptz not null default now()
);

create table if not exists public.provider_blocked_dates (
  id           uuid primary key default gen_random_uuid(),
  provider_id  uuid references public.providers(id) on delete cascade,
  blocked_date date,
  created_at   timestamptz not null default now()
);

-- =============================================================================
-- 2. BOOKINGS  (column list CONFIRMED via live probe)
-- =============================================================================

create table if not exists public.bookings (
  id                        uuid primary key default gen_random_uuid(),
  user_id                   uuid references auth.users(id) on delete set null,
  provider_id               uuid references public.providers(id) on delete set null,
  service_id                uuid references public.provider_services(id) on delete set null,
  service_name              text,
  requested_date            date,
  requested_time            text,
  appointment_time          timestamptz,
  message                   text,
  status                    text not null default 'pending',
  created_at                timestamptz not null default now(),
  client_checked_in_at      timestamptz,
  provider_confirmed_at     timestamptz,
  provider_first_response_at timestamptz,
  completed_at              timestamptz,
  cancelled_at              timestamptz,
  cancellation_reason       text,
  cancelled_by              text,
  cancellation_actor        text,
  -- payments
  stripe_payment_intent_id  text,
  payment_status            text not null default 'unpaid',
  payment_amount            numeric,
  payment_authorized_at     timestamptz,
  payment_captured_at       timestamptz,
  payment_finalized         boolean not null default false,
  capture_scheduled_for     timestamptz,
  stripe_last_event_id      text,
  stripe_last_event_at      timestamptz,
  refund_status             text not null default 'none',
  -- issues / safety / moderation
  issue_reported            boolean not null default false,
  issue_reported_at         timestamptz,
  issue_reason              text,
  under_review              boolean not null default false,
  dispute_flag              boolean not null default false,
  no_show_flag              boolean not null default false,
  provider_safety_notes     text,
  client_safety_notes       text,
  admin_resolution_notes    text
);

-- =============================================================================
-- 3. MESSAGING  (NOTE: table is SINGULAR `conversation`, confirmed in code)
-- =============================================================================

create table if not exists public.conversation (
  id              uuid primary key default gen_random_uuid(),
  client_id       uuid references auth.users(id) on delete cascade,
  provider_id     uuid references public.providers(id) on delete cascade,
  booking_id      uuid references public.bookings(id) on delete set null,
  last_message_at timestamptz,
  created_at      timestamptz not null default now()
);

create table if not exists public.messages (
  id              uuid primary key default gen_random_uuid(),
  conversation_id uuid references public.conversation(id) on delete cascade,
  sender_id       uuid references auth.users(id) on delete set null,
  content         text,
  is_read         boolean not null default false,
  created_at      timestamptz not null default now()
);

-- =============================================================================
-- 4. CONTENT (portfolio / posts / reels) + engagement
-- =============================================================================

create table if not exists public.posts (
  id            uuid primary key default gen_random_uuid(),
  provider_id   uuid references public.providers(id) on delete cascade,
  media_url     text,
  media_type    text,               -- 'image' | 'video'
  thumbnail_url text,
  content_type  text,               -- 'portfolio' | 'post' | 'reel'
  visibility    text not null default 'public',
  caption       text,
  is_active     boolean not null default true,
  is_demo       boolean not null default false,
  sort_order    integer,
  like_count    integer not null default 0,   -- trigger maintained
  save_count    integer not null default 0,   -- trigger maintained
  comment_count integer not null default 0,   -- trigger maintained
  created_at    timestamptz not null default now()
);

create table if not exists public.post_likes (
  user_id    uuid references auth.users(id) on delete cascade,
  post_id    uuid references public.posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, post_id)
);

create table if not exists public.post_saves (
  user_id    uuid references auth.users(id) on delete cascade,
  post_id    uuid references public.posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, post_id)
);

create table if not exists public.post_comments (
  id           uuid primary key default gen_random_uuid(),
  post_id      uuid references public.posts(id) on delete cascade,
  user_id      uuid references auth.users(id) on delete cascade,
  comment_text text,
  created_at   timestamptz not null default now()
);

create table if not exists public.saved_providers (
  user_id     uuid references auth.users(id) on delete cascade,
  provider_id uuid references public.providers(id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (user_id, provider_id)
);

create table if not exists public.provider_follows (
  follower_user_id uuid references auth.users(id) on delete cascade,
  provider_id      uuid references public.providers(id) on delete cascade,
  created_at       timestamptz not null default now(),
  primary key (follower_user_id, provider_id)
);

-- =============================================================================
-- 5. COMMUNITY HUB (provider-only)
-- =============================================================================

create table if not exists public.community_posts (
  id          uuid primary key default gen_random_uuid(),
  provider_id uuid references public.providers(id) on delete cascade,
  user_id     uuid references auth.users(id) on delete cascade,
  content     text,
  category    text not null default 'general',
  like_count  integer not null default 0,   -- trigger maintained
  reply_count integer not null default 0,    -- trigger maintained
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

create table if not exists public.community_replies (
  id          uuid primary key default gen_random_uuid(),
  post_id     uuid references public.community_posts(id) on delete cascade,
  provider_id uuid references public.providers(id) on delete cascade,
  user_id     uuid references auth.users(id) on delete cascade,
  content     text,
  created_at  timestamptz not null default now()
);

create table if not exists public.community_post_likes (
  user_id    uuid references auth.users(id) on delete cascade,
  post_id    uuid references public.community_posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, post_id)
);

create table if not exists public.community_bookmarks (
  user_id    uuid references auth.users(id) on delete cascade,
  post_id    uuid references public.community_posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, post_id)
);

create table if not exists public.community_reports (
  id                uuid primary key default gen_random_uuid(),
  reporter_user_id  uuid references auth.users(id) on delete cascade,
  post_id           uuid references public.community_posts(id) on delete cascade,
  reason            text,
  created_at        timestamptz not null default now()
);

-- =============================================================================
-- 6. BARTER
-- =============================================================================

create table if not exists public.barter_offers (
  id               uuid primary key default gen_random_uuid(),
  provider_id      uuid references public.providers(id) on delete cascade,
  user_id          uuid references auth.users(id) on delete cascade,
  offering_service text,
  seeking_service  text,
  offering_value   numeric,
  notes            text,
  is_active        boolean not null default true,
  created_at       timestamptz not null default now()
);

create table if not exists public.barter_interests (
  id                    uuid primary key default gen_random_uuid(),
  offer_id              uuid references public.barter_offers(id) on delete cascade,
  interested_provider_id uuid references public.providers(id) on delete cascade,
  interested_user_id    uuid references auth.users(id) on delete cascade,
  message               text,
  status                text not null default 'pending',  -- pending | accepted | declined
  created_at            timestamptz not null default now()
);

-- =============================================================================
-- 7. CARE HUB (client rebook reminders)
-- =============================================================================

create table if not exists public.care_reminders (
  id               uuid primary key default gen_random_uuid(),
  client_user_id   uuid references auth.users(id) on delete cascade,
  provider_id      uuid references public.providers(id) on delete set null,
  service_name     text,
  interval_days    integer,
  last_booked_at   timestamptz,
  next_reminder_at timestamptz,
  is_active        boolean not null default true,
  created_at       timestamptz not null default now()
);

-- =============================================================================
-- 8. CONTRACTS
-- =============================================================================

create table if not exists public.contracts (
  id            uuid primary key default gen_random_uuid(),
  provider_id   uuid unique references public.providers(id) on delete cascade,
  user_id       uuid references auth.users(id) on delete cascade,
  title         text,
  body          text not null default '',
  contract_type text not null default 'text',  -- 'text' | 'pdf'
  pdf_url       text,
  pdf_filename  text,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz
);

create table if not exists public.contract_signatures (
  id             uuid primary key default gen_random_uuid(),
  contract_id    uuid references public.contracts(id) on delete cascade,
  booking_id     uuid unique references public.bookings(id) on delete cascade,
  client_user_id uuid references auth.users(id) on delete cascade,
  signature_url  text,
  signed_at      timestamptz,
  status         text not null default 'pending',  -- pending | signed | declined
  created_at     timestamptz not null default now()
);

-- =============================================================================
-- 9. REVIEWS + REPORTS
-- =============================================================================

create table if not exists public.provider_reviews (
  id               uuid primary key default gen_random_uuid(),
  booking_id       uuid unique references public.bookings(id) on delete cascade,
  provider_id      uuid references public.providers(id) on delete cascade,
  reviewer_user_id uuid references auth.users(id) on delete set null,
  rating           integer,
  review_text      text,
  tags             text[],
  created_at       timestamptz not null default now()
);

create table if not exists public.client_reviews (
  id                  uuid primary key default gen_random_uuid(),
  booking_id          uuid unique references public.bookings(id) on delete cascade,
  client_user_id      uuid references auth.users(id) on delete set null,
  reviewer_provider_id uuid references public.providers(id) on delete cascade,
  rating              integer,
  -- structured accountability dimensions
  showed_up           boolean,
  on_time             boolean,
  followed_policy     boolean,
  payment_completed   boolean,
  private_note        text,
  created_at          timestamptz not null default now()
);

create table if not exists public.reports (
  id               uuid primary key default gen_random_uuid(),
  booking_id       uuid references public.bookings(id) on delete set null,
  reporter_user_id uuid references auth.users(id) on delete set null,
  report_type      text,
  report_reason    text,
  created_at       timestamptz not null default now()
);

-- =============================================================================
-- 10. STORAGE BUCKETS
-- =============================================================================
insert into storage.buckets (id, name, public) values
  ('posts-media',          'posts-media',          true),
  ('provider-media',       'provider-media',       true),
  ('contract-pdfs',        'contract-pdfs',        false),
  ('contract-signatures',  'contract-signatures',  false)
on conflict (id) do nothing;

-- =============================================================================
-- 11. DENORMALIZED-COUNT TRIGGERS
-- Keep like/save/comment/reply counts in sync so the client never has to.
-- =============================================================================

create or replace function public.bump_post_like_count() returns trigger language plpgsql as $$
begin
  if (tg_op = 'INSERT') then
    update public.posts set like_count = like_count + 1 where id = new.post_id;
  elsif (tg_op = 'DELETE') then
    update public.posts set like_count = greatest(0, like_count - 1) where id = old.post_id;
  end if;
  return null;
end; $$;
drop trigger if exists trg_post_like_count on public.post_likes;
create trigger trg_post_like_count after insert or delete on public.post_likes
  for each row execute function public.bump_post_like_count();

create or replace function public.bump_post_save_count() returns trigger language plpgsql as $$
begin
  if (tg_op = 'INSERT') then
    update public.posts set save_count = save_count + 1 where id = new.post_id;
  elsif (tg_op = 'DELETE') then
    update public.posts set save_count = greatest(0, save_count - 1) where id = old.post_id;
  end if;
  return null;
end; $$;
drop trigger if exists trg_post_save_count on public.post_saves;
create trigger trg_post_save_count after insert or delete on public.post_saves
  for each row execute function public.bump_post_save_count();

create or replace function public.bump_post_comment_count() returns trigger language plpgsql as $$
begin
  if (tg_op = 'INSERT') then
    update public.posts set comment_count = comment_count + 1 where id = new.post_id;
  elsif (tg_op = 'DELETE') then
    update public.posts set comment_count = greatest(0, comment_count - 1) where id = old.post_id;
  end if;
  return null;
end; $$;
drop trigger if exists trg_post_comment_count on public.post_comments;
create trigger trg_post_comment_count after insert or delete on public.post_comments
  for each row execute function public.bump_post_comment_count();

create or replace function public.bump_community_like_count() returns trigger language plpgsql as $$
begin
  if (tg_op = 'INSERT') then
    update public.community_posts set like_count = like_count + 1 where id = new.post_id;
  elsif (tg_op = 'DELETE') then
    update public.community_posts set like_count = greatest(0, like_count - 1) where id = old.post_id;
  end if;
  return null;
end; $$;
drop trigger if exists trg_community_like_count on public.community_post_likes;
create trigger trg_community_like_count after insert or delete on public.community_post_likes
  for each row execute function public.bump_community_like_count();

create or replace function public.bump_community_reply_count() returns trigger language plpgsql as $$
begin
  if (tg_op = 'INSERT') then
    update public.community_posts set reply_count = reply_count + 1 where id = new.post_id;
  elsif (tg_op = 'DELETE') then
    update public.community_posts set reply_count = greatest(0, reply_count - 1) where id = old.post_id;
  end if;
  return null;
end; $$;
drop trigger if exists trg_community_reply_count on public.community_replies;
create trigger trg_community_reply_count after insert or delete on public.community_replies
  for each row execute function public.bump_community_reply_count();

-- =============================================================================
-- 12. ROW LEVEL SECURITY  (INTENDED HARDENED BASELINE — read README first!)
-- -----------------------------------------------------------------------------
-- These policies reflect the *intended* ownership model from the security
-- audit, NOT a verified dump of the live policies. On a FRESH project they set
-- a sane secure baseline. On an EXISTING production DB, DROP POLICY IF EXISTS
-- will remove whatever is currently live and replace it — review before running.
--
-- Ownership helper: a provider "owns" a row when the row's provider_id maps to
-- a providers row whose user_id is the caller. Inlined as a subquery below.
-- =============================================================================

alter table public.providers            enable row level security;
alter table public.clients              enable row level security;
alter table public.provider_services    enable row level security;
alter table public.provider_availability enable row level security;
alter table public.provider_blocked_dates enable row level security;
alter table public.bookings             enable row level security;
alter table public.conversation         enable row level security;
alter table public.messages             enable row level security;
alter table public.posts                enable row level security;
alter table public.post_likes           enable row level security;
alter table public.post_saves           enable row level security;
alter table public.post_comments        enable row level security;
alter table public.saved_providers      enable row level security;
alter table public.provider_follows     enable row level security;
alter table public.community_posts      enable row level security;
alter table public.community_replies    enable row level security;
alter table public.community_post_likes enable row level security;
alter table public.community_bookmarks  enable row level security;
alter table public.community_reports    enable row level security;
alter table public.barter_offers        enable row level security;
alter table public.barter_interests     enable row level security;
alter table public.care_reminders       enable row level security;
alter table public.contracts            enable row level security;
alter table public.contract_signatures  enable row level security;
alter table public.provider_reviews     enable row level security;
alter table public.client_reviews       enable row level security;
alter table public.reports              enable row level security;
-- categories is public reference data; RLS optional (left readable).

-- ---- providers: public read, self-write ------------------------------------
drop policy if exists providers_select_all on public.providers;
create policy providers_select_all on public.providers for select using (true);
drop policy if exists providers_insert_self on public.providers;
create policy providers_insert_self on public.providers for insert with check (auth.uid() = user_id);
drop policy if exists providers_update_self on public.providers;
create policy providers_update_self on public.providers for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- HARDENING (audit critical #2): even with the self-update policy above, a
-- provider must NOT be able to grant themselves verification / featuring /
-- payment capability / inflated stats. Revoke column-level UPDATE so only the
-- service role (or a trigger) can change them.
revoke update (
  is_approved, is_featured, is_trending,
  verification_status, identity_verified, business_verified,
  stripe_charges_enabled, stripe_payouts_enabled, stripe_onboarding_complete,
  stripe_details_submitted, stripe_account_id,
  rating, average_rating, review_count,
  total_bookings, completed_count, no_show_count, follower_count
) on public.providers from authenticated;

-- ---- clients: strictly self ------------------------------------------------
drop policy if exists clients_rw_self on public.clients;
create policy clients_rw_self on public.clients for all
  using (id = auth.uid()) with check (id = auth.uid());

-- ---- provider_services / availability / blocked_dates: public read, owner write
drop policy if exists provider_services_select on public.provider_services;
create policy provider_services_select on public.provider_services for select using (true);
drop policy if exists provider_services_write on public.provider_services;
create policy provider_services_write on public.provider_services for all
  using (provider_id in (select id from public.providers where user_id = auth.uid()))
  with check (provider_id in (select id from public.providers where user_id = auth.uid()));

drop policy if exists provider_availability_select on public.provider_availability;
create policy provider_availability_select on public.provider_availability for select using (true);
drop policy if exists provider_availability_write on public.provider_availability;
create policy provider_availability_write on public.provider_availability for all
  using (provider_id in (select id from public.providers where user_id = auth.uid()))
  with check (provider_id in (select id from public.providers where user_id = auth.uid()));

drop policy if exists provider_blocked_select on public.provider_blocked_dates;
create policy provider_blocked_select on public.provider_blocked_dates for select using (true);
drop policy if exists provider_blocked_write on public.provider_blocked_dates;
create policy provider_blocked_write on public.provider_blocked_dates for all
  using (provider_id in (select id from public.providers where user_id = auth.uid()))
  with check (provider_id in (select id from public.providers where user_id = auth.uid()));

-- ---- bookings: participant read; client creates; participants update -------
-- (HARDENING #3: a stricter WITH CHECK per role is still owed — clients should
--  not be able to set status='completed'/no_show_flag/payment_*; enforce via
--  column grants or a trigger. This baseline scopes rows to participants.)
drop policy if exists bookings_select_participant on public.bookings;
create policy bookings_select_participant on public.bookings for select using (
  auth.uid() = user_id
  or provider_id in (select id from public.providers where user_id = auth.uid())
);
drop policy if exists bookings_insert_client on public.bookings;
create policy bookings_insert_client on public.bookings for insert with check (auth.uid() = user_id);
drop policy if exists bookings_update_participant on public.bookings;
create policy bookings_update_participant on public.bookings for update using (
  auth.uid() = user_id
  or provider_id in (select id from public.providers where user_id = auth.uid())
);

-- ---- messaging: only conversation participants -----------------------------
drop policy if exists conversation_participant on public.conversation;
create policy conversation_participant on public.conversation for all using (
  auth.uid() = client_id
  or provider_id in (select id from public.providers where user_id = auth.uid())
) with check (
  auth.uid() = client_id
  or provider_id in (select id from public.providers where user_id = auth.uid())
);
drop policy if exists messages_select_participant on public.messages;
create policy messages_select_participant on public.messages for select using (
  conversation_id in (
    select id from public.conversation
    where client_id = auth.uid()
       or provider_id in (select id from public.providers where user_id = auth.uid())
  )
);
drop policy if exists messages_insert_sender on public.messages;
create policy messages_insert_sender on public.messages for insert with check (
  auth.uid() = sender_id
  and conversation_id in (
    select id from public.conversation
    where client_id = auth.uid()
       or provider_id in (select id from public.providers where user_id = auth.uid())
  )
);
drop policy if exists messages_update_participant on public.messages;
create policy messages_update_participant on public.messages for update using (
  conversation_id in (
    select id from public.conversation
    where client_id = auth.uid()
       or provider_id in (select id from public.providers where user_id = auth.uid())
  )
);

-- ---- posts + engagement: public read of active; owner writes ----------------
drop policy if exists posts_select_active on public.posts;
create policy posts_select_active on public.posts for select using (is_active or provider_id in (select id from public.providers where user_id = auth.uid()));
drop policy if exists posts_write_owner on public.posts;
create policy posts_write_owner on public.posts for all
  using (provider_id in (select id from public.providers where user_id = auth.uid()))
  with check (provider_id in (select id from public.providers where user_id = auth.uid()));

drop policy if exists post_likes_select on public.post_likes;
create policy post_likes_select on public.post_likes for select using (true);
drop policy if exists post_likes_self on public.post_likes;
create policy post_likes_self on public.post_likes for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists post_saves_self on public.post_saves;
create policy post_saves_self on public.post_saves for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists post_comments_select on public.post_comments;
create policy post_comments_select on public.post_comments for select using (true);
drop policy if exists post_comments_self on public.post_comments;
create policy post_comments_self on public.post_comments for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists saved_providers_self on public.saved_providers;
create policy saved_providers_self on public.saved_providers for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists provider_follows_self on public.provider_follows;
create policy provider_follows_self on public.provider_follows for all using (follower_user_id = auth.uid()) with check (follower_user_id = auth.uid());

-- ---- community: provider-only read; author writes --------------------------
-- (HARDENING #1d: the "provider-only" gate MUST live here, not just in the UI.)
drop policy if exists community_posts_provider_read on public.community_posts;
create policy community_posts_provider_read on public.community_posts for select using (
  exists (select 1 from public.providers where user_id = auth.uid())
);
drop policy if exists community_posts_author_write on public.community_posts;
create policy community_posts_author_write on public.community_posts for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists community_replies_provider_read on public.community_replies;
create policy community_replies_provider_read on public.community_replies for select using (
  exists (select 1 from public.providers where user_id = auth.uid())
);
drop policy if exists community_replies_author_write on public.community_replies;
create policy community_replies_author_write on public.community_replies for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists community_likes_self on public.community_post_likes;
create policy community_likes_self on public.community_post_likes for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists community_bookmarks_self on public.community_bookmarks;
create policy community_bookmarks_self on public.community_bookmarks for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists community_reports_insert on public.community_reports;
create policy community_reports_insert on public.community_reports for insert
  with check (auth.uid() = reporter_user_id);

-- ---- barter: any provider reads offers; owners manage ----------------------
drop policy if exists barter_offers_provider_read on public.barter_offers;
create policy barter_offers_provider_read on public.barter_offers for select using (
  exists (select 1 from public.providers where user_id = auth.uid())
);
drop policy if exists barter_offers_owner_write on public.barter_offers;
create policy barter_offers_owner_write on public.barter_offers for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists barter_interests_read on public.barter_interests;
create policy barter_interests_read on public.barter_interests for select using (
  auth.uid() = interested_user_id
  or offer_id in (select id from public.barter_offers where user_id = auth.uid())
);
drop policy if exists barter_interests_insert on public.barter_interests;
create policy barter_interests_insert on public.barter_interests for insert
  with check (auth.uid() = interested_user_id);
drop policy if exists barter_interests_owner_update on public.barter_interests;
create policy barter_interests_owner_update on public.barter_interests for update using (
  offer_id in (select id from public.barter_offers where user_id = auth.uid())
);

-- ---- care reminders: strictly the owning client ----------------------------
drop policy if exists care_reminders_self on public.care_reminders;
create policy care_reminders_self on public.care_reminders for all
  using (client_user_id = auth.uid()) with check (client_user_id = auth.uid());

-- ---- contracts: provider owns; signatures visible to participants ----------
drop policy if exists contracts_owner_write on public.contracts;
create policy contracts_owner_write on public.contracts for all
  using (provider_id in (select id from public.providers where user_id = auth.uid()))
  with check (provider_id in (select id from public.providers where user_id = auth.uid()));
drop policy if exists contracts_public_read on public.contracts;
create policy contracts_public_read on public.contracts for select using (true);
-- ^ clients must read a provider's contract while booking; if you want to
--   restrict to active booking participants only, tighten this later.

drop policy if exists contract_sig_participant on public.contract_signatures;
create policy contract_sig_participant on public.contract_signatures for select using (
  auth.uid() = client_user_id
  or contract_id in (
    select c.id from public.contracts c
    join public.providers p on p.id = c.provider_id
    where p.user_id = auth.uid()
  )
);
drop policy if exists contract_sig_insert_client on public.contract_signatures;
create policy contract_sig_insert_client on public.contract_signatures for insert
  with check (auth.uid() = client_user_id);

-- ---- reviews + reports -----------------------------------------------------
drop policy if exists provider_reviews_read on public.provider_reviews;
create policy provider_reviews_read on public.provider_reviews for select using (true);
drop policy if exists provider_reviews_author on public.provider_reviews;
create policy provider_reviews_author on public.provider_reviews for insert
  with check (auth.uid() = reviewer_user_id);

drop policy if exists client_reviews_author on public.client_reviews;
create policy client_reviews_author on public.client_reviews for insert
  with check (reviewer_provider_id in (select id from public.providers where user_id = auth.uid()));
drop policy if exists client_reviews_read on public.client_reviews;
create policy client_reviews_read on public.client_reviews for select using (
  reviewer_provider_id in (select id from public.providers where user_id = auth.uid())
  or auth.uid() = client_user_id
);

drop policy if exists reports_insert_self on public.reports;
create policy reports_insert_self on public.reports for insert
  with check (auth.uid() = reporter_user_id);

-- =============================================================================
-- END BASELINE
-- =============================================================================
